### ISSUE TITLE
users still prevented from submitting to queue after it has been removed

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-accounting#333] opened 2023-03-27 23:20 UTC
Possibly related to #332, if I delete a queue with `flux account delete-queue ...`, then run `flux account-priority-update`, users who were not given access to it continue to be unable to submit to it.

**Comment by cmoussa1** [comment] 2023-03-28 01:57
Sorry, I think I could probably use a little more clarification here. 😅 This sounds like expected behavior? If a queue is removed from the flux-accounting database, shouldn't users **not** be able to submit jobs under that queue, since it does not exist?

**Comment by ryanday36** [comment] 2023-03-28 14:49
The queue still exists on the cluster, just not in the DB. I expected it to revert to the behavior before the queue had been added where the plugin skips the check for whether or not the user has the queue.

**Comment by cmoussa1** [comment] 2023-03-30 23:57
This should also be resolved by #334, so I will close this too.

**Closed by cmoussa1** 2023-03-30 23:57 UTC
Labels: bug
